### ISSUE TITLE
Internal Error after enabling authentication

### ISSUE THREAD

**Issue by noisytoken** [judge0/api#101]
I have enabled the authentication by setting `AUTHN_TOKEN` (in `judge0-api.conf`) to `12345`.

After that every request I make results in 500 Internal server error.

Request: http://localhost:3000/authenticate?X-Auth-Token=12345 

Response:

```
{
    "status": 500,
    "error": "Internal Server Error",
    "exception": "#<NoMethodError: undefined method `split' for 12345:Fixnum>",
    "traces": {
        "Application Trace": [
            {
                "id": 0,
                "trace": "app/controllers/sessions_controller.rb:27:in `safe_compare'"
            },
            {
                "id": 1,
                "trace": "app/controllers/sessions_controller.rb:16:in `authenticate_request'"
            }
        ],
        "Framework Trace": [
            {
                "id": 2,
                "trace": "activesupport (5.0.7.2) lib/active_support/callbacks.rb:382:in `block in make_lambda'"
            },
            {
                "id": 3,
                "trace": "activesupport (5.0.7.2) lib/active_support/callbacks.rb:169:in `block (2 levels) in halting'"
            },
            {
                "id": 4,
                "trace": "actionpack (5.0.7.2) lib/abstract_controller/callbacks.rb:12:in `block (2 levels) in <module:Callbacks>'"
            },
            {
                "id": 5,
                "trace": "activesupport (5.0.7.2) lib/active_support/callbacks.rb:170:in `block in halting'"
            },
            {
                "id": 6,
                "trace": "activesupport (5.0.7.2) lib/active_support/callbacks.rb:454:in `block in call'"
            },
            {
                "id": 7,
                "trace": "activesupport (5.0.7.2) lib/active_support/callbacks.rb:454:in `each'"
            },
            {
                "id": 8,
                "trace": "activesupport (5.0.7.2) lib/active_support/callbacks.rb:454:in `call'"
            },
            {
                "id": 9,
                "trace": "activesupport (5.0.7.2) lib/active_support/callbacks.rb:101:in `__run_callbacks__'"
            },
            {
                "id": 10,
                "trace": "activesupport (5.0.7.2) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'"
            },
            {
                "id": 11,
                "trace": "activesupport (5.0.7.2) lib/active_support/callbacks.rb:90:in `run_callbacks'"
            },
            {
                "id": 12,
                "trace": "actionpack (5.0.7.2) lib/abstract_controller/callbacks.rb:19:in `process_action'"
            },
            {
                "id": 13,
                "trace": "actionpack (5.0.7.2) lib/action_controller/metal/rescue.rb:20:in `process_action'"
            },
            {
                "id": 14,
                "trace": "actionpack (5.0.7.2) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'"
            },
            {
                "id": 15,
                "trace": "activesupport (5.0.7.2) lib/active_support/notifications.rb:164:in `block in instrument'"
            },
            {
                "id": 16,
                "trace": "activesupport (5.0.7.2) lib/active_support/notifications/instrumenter.rb:21:in `instrument'"
            },
            {
                "id": 17,
                "trace": "activesupport (5.0.7.2) lib/active_support/notifications.rb:164:in `instrument'"
            },
            {
                "id": 18,
                "trace": "actionpack (5.0.7.2) lib/action_controller/metal/instrumentation.rb:30:in `process_action'"
            },
            {
                "id": 19,
                "trace": "actionpack (5.0.7.2) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'"
            },
            {
                "id": 20,
                "trace": "activerecord (5.0.7.2) lib/active_record/railties/controller_runtime.rb:18:in `process_action'"
            },
           
          ...
            {
                "id": 60,
                "trace": "puma (3.12.1) lib/puma/server.rb:334:in `block in run'"
            },
            {
                "id": 61,
                "trace": "puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'"
            }
        ]
    }
}
```

I am still running in development.

**Comment by hermanzdosilovic** [comment]
Fixed with [v1.3.0](https://github.com/judge0/api/releases/tag/v1.3.0).
