### ISSUE TITLE
memory issue on gcp (wondering if you have any hints.)

### ISSUE THREAD

**Issue by OliverwengFiltered** [judge0/api#148]
```
{
"status": 500,
"error": "Internal Server Error",
"exception": "#<Errno::ENOMEM: Cannot allocate memory - isolate>",
"traces": {
"Application Trace": [
{
"id": 2,
"trace": "app/controllers/info_controller.rb:3:in `<class:InfoController>'"
},
{
"id": 3,
"trace": "app/controllers/info_controller.rb:1:in `<top (required)>'"
}
],
"Framework Trace": [
{
"id": 0,
"trace": "activesupport (5.0.7.2) lib/active_support/core_ext/kernel/agnostics.rb:7:in ``'"
},
{
"id": 1,
"trace": "activesupport (5.0.7.2) lib/active_support/core_ext/kernel/agnostics.rb:7:in ``'"
},
{
"id": 4,
"trace": "activesupport (5.0.7.2) lib/active_support/dependencies.rb:478:in `load'"
},
{
"id": 5,
"trace": "activesupport (5.0.7.2) lib/active_support/dependencies.rb:478:in `block in load_file'"
},
{
"id": 6,
"trace": "activesupport (5.0.7.2) lib/active_support/dependencies.rb:663:in `new_constants_in'"
},
{
"id": 7,
"trace": "activesupport (5.0.7.2) lib/active_support/dependencies.rb:477:in `load_file'"
},
{
"id": 8,
"trace": "activesupport (5.0.7.2) lib/active_support/dependencies.rb:375:in `block in require_or_load'"
},
{
"id": 9,
"trace": "activesupport (5.0.7.2) lib/active_support/dependencies.rb:37:in `block in load_interlock'"
},
{
"id": 10,
"trace": "activesupport (5.0.7.2) lib/active_support/dependencies/interlock.rb:12:in `block in loading'"
},
{
"id": 11,
"trace": "activesupport (5.0.7.2) lib/active_support/concurrency/share_lock.rb:150:in `exclusive'"
},
{
"id": 12,
"trace": "activesupport (5.0.7.2) lib/active_support/dependencies/interlock.rb:11:in `loading'"
},
{
"id": 13,
"trace": "activesupport (5.0.7.2) lib/active_support/dependencies.rb:37:in `load_interlock'"
},
{
"id": 14,
"trace": "activesupport (5.0.7.2) lib/active_support/dependencies.rb:358:in `require_or_load'"
},
{
"id": 15,
"trace": "activesupport (5.0.7.2) lib/active_support/dependencies.rb:512:in `load_missing_constant'"
},
{
"id": 16,
"trace": "activesupport (5.0.7.2) lib/active_support/dependencies.rb:203:in `const_missing'"
},
{
"id": 17,
"trace": "activesupport (5.0.7.2) lib/active_support/inflector/methods.rb:268:in `const_get'"
},
{
"id": 18,
"trace": "activesupport (5.0.7.2) lib/active_support/inflector/methods.rb:268:in `block in constantize'"
},
{
"id": 19,
"trace": "activesupport (5.0.7.2) lib/active_support/inflector/methods.rb:266:in `each'"
},
{
"id": 20,
"trace": "activesupport (5.0.7.2) lib/active_support/inflector/methods.rb:266:in `inject'"
},
{
"id": 21,
"trace": "activesupport (5.0.7.2) lib/active_support/inflector/methods.rb:266:in `constantize'"
},
{
"id": 22,
"trace": "activesupport (5.0.7.2) lib/active_support/dependencies.rb:584:in `get'"
},
{
"id": 23,
"trace": "activesupport (5.0.7.2) lib/active_support/dependencies.rb:615:in `constantize'"
},
{
"id": 24,
"trace": "actionpack (5.0.7.2) lib/action_dispatch/http/request.rb:81:in `controller_class'"
},
{
"id": 25,
"trace": "actionpack (5.0.7.2) lib/action_dispatch/routing/route_set.rb:44:in `controller'"
},
{
"id": 26,
"trace": "actionpack (5.0.7.2) lib/action_dispatch/routing/route_set.rb:30:in `serve'"
},
{
"id": 27,
"trace": "actionpack (5.0.7.2) lib/action_dispatch/journey/router.rb:39:in `block in serve'"
},
{
"id": 28,
"trace": "actionpack (5.0.7.2) lib/action_dispatch/journey/router.rb:26:in `each'"
},
{
"id": 29,
"trace": "actionpack (5.0.7.2) lib/action_dispatch/journey/router.rb:26:in `serve'"
},
{
"id": 30,
"trace": "actionpack (5.0.7.2) lib/action_dispatch/routing/route_set.rb:727:in `call'"
},
{
"id": 31,
"trace": "rack (2.0.8) lib/rack/etag.rb:25:in `call'"
},
{
"id": 32,
"trace": "rack (2.0.8) lib/rack/conditional_get.rb:25:in `call'"
},
{
"id": 33,
"trace": "rack (2.0.8) lib/rack/head.rb:12:in `call'"
},
{
"id": 34,
"trace": "activerecord (5.0.7.2) lib/active_record/migration.rb:553:in `call'"
},
{
"id": 35,
"trace": "actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'"
},
{
"id": 36,
"trace": "activesupport (5.0.7.2) lib/active_support/callbacks.rb:97:in `__run_callbacks__'"
},
{
"id": 37,
"trace": "activesupport (5.0.7.2) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'"
},
{
"id": 38,
"trace": "activesupport (5.0.7.2) lib/active_support/callbacks.rb:90:in `run_callbacks'"
},
{
"id": 39,
"trace": "actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:36:in `call'"
},
{
"id": 40,
"trace": "actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'"
},
{
"id": 41,
"trace": "actionpack (5.0.7.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'"
},
{
"id": 42,
"trace": "actionpack (5.0.7.2) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'"
},
{
"id": 43,
"trace": "actionpack (5.0.7.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'"
},
{
"id": 44,
"trace": "railties (5.0.7.2) lib/rails/rack/logger.rb:36:in `call_app'"
},
{
"id": 45,
"trace": "railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `block in call'"
},
{
"id": 46,
"trace": "activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'"
},
{
"id": 47,
"trace": "activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:26:in `tagged'"
},
{
"id": 48,
"trace": "activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `tagged'"
},
{
"id": 49,
"trace": "railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `call'"
},
{
"id": 50,
"trace": "actionpack (5.0.7.2) lib/action_dispatch/middleware/request_id.rb:24:in `call'"
},
{
"id": 51,
"trace": "rack (2.0.8) lib/rack/runtime.rb:22:in `call'"
},
{
"id": 52,
"trace": "activesupport (5.0.7.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'"
},
{
"id": 53,
"trace": "actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'"
},
{
"id": 54,
"trace": "actionpack (5.0.7.2) lib/action_dispatch/middleware/static.rb:136:in `call'"
},
{
"id": 55,
"trace": "rack (2.0.8) lib/rack/sendfile.rb:111:in `call'"
},
{
"id": 56,
"trace": "rack-cors (1.1.0) lib/rack/cors.rb:100:in `call'"
},
{
"id": 57,
"trace": "railties (5.0.7.2) lib/rails/engine.rb:522:in `call'"
},
{
"id": 58,
"trace": "puma (3.12.2) lib/puma/configuration.rb:227:in `call'"
},
{
"id": 59,
"trace": "puma (3.12.2) lib/puma/server.rb:674:in `handle_request'"
},
{
"id": 60,
"trace": "puma (3.12.2) lib/puma/server.rb:476:in `process_client'"
},
{
"id": 61,
"trace": "puma (3.12.2) lib/puma/server.rb:334:in `block in run'"
},
{
"id": 62,
"trace": "puma (3.12.2) lib/puma/thread_pool.rb:135:in `block in spawn_thread'"
}
],
"Full Trace": [
{
"id": 0,
"trace": "activesupport (5.0.7.2) lib/active_support/core_ext/kernel/agnostics.rb:7:in ``'"
},
{
"id": 1,
"trace": "activesupport (5.0.7.2) lib/active_support/core_ext/kernel/agnostics.rb:7:in ``'"
},
{
"id": 2,
"trace": "app/controllers/info_controller.rb:3:in `<class:InfoController>'"
},
{
"id": 3,
"trace": "app/controllers/info_controller.rb:1:in `<top (required)>'"
},
{
"id": 4,
"trace": "activesupport (5.0.7.2) lib/active_support/dependencies.rb:478:in `load'"
},
{
"id": 5,
"trace": "activesupport (5.0.7.2) lib/active_support/dependencies.rb:478:in `block in load_file'"
},
{
"id": 6,
"trace": "activesupport (5.0.7.2) lib/active_support/dependencies.rb:663:in `new_constants_in'"
},
{
"id": 7,
"trace": "activesupport (5.0.7.2) lib/active_support/dependencies.rb:477:in `load_file'"
},
{
"id": 8,
"trace": "activesupport (5.0.7.2) lib/active_support/dependencies.rb:375:in `block in require_or_load'"
},
{
"id": 9,
"trace": "activesupport (5.0.7.2) lib/active_support/dependencies.rb:37:in `block in load_interlock'"
},
{
"id": 10,
"trace": "activesupport (5.0.7.2) lib/active_support/dependencies/interlock.rb:12:in `block in loading'"
},
{
"id": 11,
"trace": "activesupport (5.0.7.2) lib/active_support/concurrency/share_lock.rb:150:in `exclusive'"
},
{
"id": 12,
"trace": "activesupport (5.0.7.2) lib/active_support/dependencies/interlock.rb:11:in `loading'"
},
{
"id": 13,
"trace": "activesupport (5.0.7.2) lib/active_support/dependencies.rb:37:in `load_interlock'"
},
{
"id": 14,
"trace": "activesupport (5.0.7.2) lib/active_support/dependencies.rb:358:in `require_or_load'"
},
{
"id": 15,
"trace": "activesupport (5.0.7.2) lib/active_support/dependencies.rb:512:in `load_missing_constant'"
},
{
"id": 16,
"trace": "activesupport (5.0.7.2) lib/active_support/dependencies.rb:203:in `const_missing'"
},
{
"id": 17,
"trace": "activesupport (5.0.7.2) lib/active_support/inflector/methods.rb:268:in `const_get'"
},
{
"id": 18,
"trace": "activesupport (5.0.7.2) lib/active_support/inflector/methods.rb:268:in `block in constantize'"
},
{
"id": 19,
"trace": "activesupport (5.0.7.2) lib/active_support/inflector/methods.rb:266:in `each'"
},
{
"id": 20,
"trace": "activesupport (5.0.7.2) lib/active_support/inflector/methods.rb:266:in `inject'"
},
{
"id": 21,
"trace": "activesupport (5.0.7.2) lib/active_support/inflector/methods.rb:266:in `constantize'"
},
{
"id": 22,
"trace": "activesupport (5.0.7.2) lib/active_support/dependencies.rb:584:in `get'"
},
{
"id": 23,
"trace": "activesupport (5.0.7.2) lib/active_support/dependencies.rb:615:in `constantize'"
},
{
"id": 24,
"trace": "actionpack (5.0.7.2) lib/action_dispatch/http/request.rb:81:in `controller_class'"
},
{
"id": 25,
"trace": "actionpack (5.0.7.2) lib/action_dispatch/routing/route_set.rb:44:in `controller'"
},
{
"id": 26,
"trace": "actionpack (5.0.7.2) lib/action_dispatch/routing/route_set.rb:30:in `serve'"
},
{
"id": 27,
"trace": "actionpack (5.0.7.2) lib/action_dispatch/journey/router.rb:39:in `block in serve'"
},
{
"id": 28,
"trace": "actionpack (5.0.7.2) lib/action_dispatch/journey/router.rb:26:in `each'"
},
{
"id": 29,
"trace": "actionpack (5.0.7.2) lib/action_dispatch/journey/router.rb:26:in `serve'"
},
{
"id": 30,
"trace": "actionpack (5.0.7.2) lib/action_dispatch/routing/route_set.rb:727:in `call'"
},
{
"id": 31,
"trace": "rack (2.0.8) lib/rack/etag.rb:25:in `call'"
},
{
"id": 32,
"trace": "rack (2.0.8) lib/rack/conditional_get.rb:25:in `call'"
},
{
"id": 33,
"trace": "rack (2.0.8) lib/rack/head.rb:12:in `call'"
},
{
"id": 34,
"trace": "activerecord (5.0.7.2) lib/active_record/migration.rb:553:in `call'"
},
{
"id": 35,
"trace": "actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'"
},
{
"id": 36,
"trace": "activesupport (5.0.7.2) lib/active_support/callbacks.rb:97:in `__run_callbacks__'"
},
{
"id": 37,
"trace": "activesupport (5.0.7.2) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'"
},
{
"id": 38,
"trace": "activesupport (5.0.7.2) lib/active_support/callbacks.rb:90:in `run_callbacks'"
},
{
"id": 39,
"trace": "actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:36:in `call'"
},
{
"id": 40,
"trace": "actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'"
},
{
"id": 41,
"trace": "actionpack (5.0.7.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'"
},
{
"id": 42,
"trace": "actionpack (5.0.7.2) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'"
},
{
"id": 43,
"trace": "actionpack (5.0.7.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'"
},
{
"id": 44,
"trace": "railties (5.0.7.2) lib/rails/rack/logger.rb:36:in `call_app'"
},
{
"id": 45,
"trace": "railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `block in call'"
},
{
"id": 46,
"trace": "activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'"
},
{
"id": 47,
"trace": "activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:26:in `tagged'"
},
{
"id": 48,
"trace": "activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `tagged'"
},
{
"id": 49,
"trace": "railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `call'"
},
{
"id": 50,
"trace": "actionpack (5.0.7.2) lib/action_dispatch/middleware/request_id.rb:24:in `call'"
},
{
"id": 51,
"trace": "rack (2.0.8) lib/rack/runtime.rb:22:in `call'"
},
{
"id": 52,
"trace": "activesupport (5.0.7.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'"
},
{
"id": 53,
"trace": "actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'"
},
{
"id": 54,
"trace": "actionpack (5.0.7.2) lib/action_dispatch/middleware/static.rb:136:in `call'"
},
{
"id": 55,
"trace": "rack (2.0.8) lib/rack/sendfile.rb:111:in `call'"
},
{
"id": 56,
"trace": "rack-cors (1.1.0) lib/rack/cors.rb:100:in `call'"
},
{
"id": 57,
"trace": "railties (5.0.7.2) lib/rails/engine.rb:522:in `call'"
},
{
"id": 58,
"trace": "puma (3.12.2) lib/puma/configuration.rb:227:in `call'"
},
{
"id": 59,
"trace": "puma (3.12.2) lib/puma/server.rb:674:in `handle_request'"
},
{
"id": 60,
"trace": "puma (3.12.2) lib/puma/server.rb:476:in `process_client'"
},
{
"id": 61,
"trace": "puma (3.12.2) lib/puma/server.rb:334:in `block in run'"
},
{
"id": 62,
"trace": "puma (3.12.2) lib/puma/thread_pool.rb:135:in `block in spawn_thread'"
}
]
}
}
```

**Comment by OliverwengFiltered** [comment]
Hi there,

it seems the garbage collection mechanism is not working in ruby backend, the memory usage is slowly going up and eventually it's gonna give this error.

Any idea of fix or hints would be very much appreciated. 

Thanks

**Comment by shivaluma** [comment]
hi, how can you deploy this project to gcp ?
can u show me the instruction,
Thank you.
